[project]
name = 'Blockchain-Based-Retail-Inventory-Allocation-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.sales-tracking]
path = 'contracts/sales-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.store-verification]
path = 'contracts/store-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
